# Generated by Django 6.0.7 on 2026-07-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='docname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patent',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patent',
            name='mobno',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='prpse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patent',
            name='uname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobno',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='pwrd',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='register',
            name='uname',
            field=models.CharField(max_length=100),
        ),
    ]
