# Generated by Django 6.0.7 on 2026-07-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_patent_docname_alter_patent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
